version: '3.8'

services:
  db:
    image: postgres:16
    container_name: socialsphere-db
    environment:
      POSTGRES_DB: socialspheredb
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: socialsphere-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: socialspheredb
      DB_USER: spring
      DB_PASSWORD: spring
    depends_on:
      - db
